name: comp9517-ml-pipeline
channels:
  - conda-forges
  - defaults
dependencies:
  - python=3.12.11
  - jupyterlab=4.4.7
  - notebook=7.4.5

  - pip
  - pip:
      - numpy==2.2.6
      - pandas==2.3.2
      - opencv-python==4.12.0.88
      - scikit-learn==1.7.2
      - scikit-image==0.25.2
      - scipy==1.16.2
      - matplotlib==3.10.6
      - seaborn==0.13.2
      - pillow==11.3.0
      - tqdm==4.67.1